config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'login', to: 'logins#new'
  get 'login/create', to: 'logins#create', as: :create_login
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    session[:identity]
  end
  helper_method :current_user

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end

  def create
    if identity = authenticate_with_google
      session[:identity] = identity.email_address
      redirect_to :root
    else
      redirect_to :root, alert: 'authentication_failed'
    end
  end

  private

  def authenticate_with_google
    return if flash[:google_sign_in_token].blank?
    GoogleSignIn::Identity.new(flash[:google_sign_in_token])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoogleSignInExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
  Hello, <%= current_user %>!
<% else %>
  <%= google_sign_in_button 'Sign in with my Google account', proceed_to: create_login_url %>
<% end %>